---
version: '3.8'

services:

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: kollinstec_db
      MYSQL_USER: kollinstec
      MYSQL_PASSWORD: kollinstec
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      DEBUG: true,
      MYSQL_DATABASE: kollinstec_db
      MYSQL_USER: kollinstec
      MYSQL_PASSWORD: kollinstec
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    depends_on:
      - db
